---
# Source: tigera-secure-ee-core/templates/kdd-crds.yaml

apiVersion: apiextensions.k8s.io/v1beta1-v-2.8
kind: CustomResourceDefinition
metadata:
  name: bgpconfigurations.crd.projectcalico.org
spec:
  scope: Cluster
  group: crd.projectcalico.org
  version: v1
  names:
    kind: BGPConfiguration
    plural: bgpconfigurations
    singular: bgpconfiguration
